version: '3.8'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY=+2x2%b5q0zx934&o*+kma^v_c2sjm3oplz_&0yyr50vkeki@at
            - DEBUG=False
        volumes:
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            # - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes: 
    postgres_data: